version: "3.7"

services:
  # mail:
  #   build:
  #     context: mail
  #     dockerfile: Dockerfile
  #   # uncomment this if you want the service to be available outside of docker network
  #   # ports:
  #   #   - 12014:12014
  #   restart: always
  #   environment:
  #     - GMAIL_USERNAME=${GMAIL_USERNAME}
  #     - GMAIL_PASSWORD=${GMAIL_PASSWORD}

  postgresql:
    image: postgres
    container_name: documenthub_postgresql
    ports:
      -  5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - planty_volume_postgres_data:/var/lib/postgresql/data/


volumes:
  planty_volume_postgres_data:
