version: "3.7"

services:
  mail:
    build:
      context: mail
      dockerfile: Dockerfile
    # uncomment this if you want the service to be available outside of docker network
    # ports:
    #   - 12014:12014
    restart: always
    environment:
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
    networks:
      - planty_mail_net

  notifications:
    build:
      context: notifications
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mail
    # uncomment this if you want the service to be available outside of docker network
    ports:
      - 12012:12012
    environment:
      MAIL_SERVICE_HOST: planty-mail
      MAIL_SERVICE_PORT: 12014
      WATERING_NOTIFICATION_STRATEGY: -1;0;1;3;6,*3
    networks:
      - planty_mail_net

  postgresql:
    image: postgres
    container_name: documenthub_postgresql
    ports:
      -  5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - planty_volume_postgres_data:/var/lib/postgresql/data/


volumes:
  planty_volume_postgres_data:

networks:
  planty_mail_net:
    driver: bridge
