# Generated by Django 4.0.3 on 2022-05-25 17:34

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=50)),
                ('watering', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('insolation', models.CharField(max_length=50)),
                ('fertilizing', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('photo', models.ImageField(default=None, upload_to='plants')),
                ('other_info', models.CharField(blank=True, default='', max_length=400)),
                ('last_watered', models.DateField(default=datetime.date.today)),
                ('last_fertilized', models.DateField(default=datetime.date.today)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.instruction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventsHistory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=400)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
