# Generated by Django 4.0.3 on 2022-04-28 03:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=50, primary_key=True)),
                ('watering', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('insolation', models.CharField(max_length=50)),
                ('fertilizing', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('other_info', models.CharField(blank=True, default='', max_length=400)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.instruction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
